### ISSUE TITLE
Can't open typescript files

### ISSUE THREAD

**Issue by fernandopasik** [eugenezinovyev/lcov-viewer#89]
**Describe the bug**
When opening an lcov.info file from typescript files the main coverage report is generated, but can't open individual files to see detailed file coverage.
Looking at a file in the tree is not a link like in the demo.

**To Reproduce**
Just open an lcov.info made from typescrip files

**Expected behavior**
Open  detailed file coverage

**Comment by eugenezinovyev** [comment]
Are you opening the file on the https://lcov-viewer.netlify.app?

**Comment by fernandopasik** [comment]
Yes, I opened with it and the overview screen show all the coverage, but I can't navigate inside the files, they are not links

<img width="738" alt="Screenshot 2024-01-11 222407" src="https://github.com/eugenezinovyev/lcov-viewer/assets/1301335/8232cc99-a389-40d7-8e30-90799dffca71">

**Comment by fernandopasik** [comment]
To give more context I'm generating the lcov.info file with the new node.js test reporter and tsx loader

node --test --experimental-test-coverage --test-reporter=lcov --test-reporter-destination=coverage/lcov.info --import tsx src/**/*

**Comment by fernandopasik** [comment]
Sorry, I also tried an lcov.info file generated with jest and also the ts files were not links nor I could dig into detail for each file

**Comment by eugenezinovyev** [comment]
Right, the issue he it that the lcov file does not contain an source code. Thus, the site cannot show anything. However, there is a package [@lcov-viewer/istanbul-report](https://www.npmjs.com/package/@lcov-viewer/istanbul-report) which you can use to generate an HTML report as an output from Jest coverage.
Here is an example of how you can add it to coverage reporters:
```
// jest.config.js
coverageReporters: [
    // other reporters
    '@lcov-viewer/istanbul-report'
],
```

**Comment by fernandopasik** [comment]
Thanks for the suggestion for jest.

I tried also the cli with this command and it generated the same output that the website.
```
lcov-viewer lcov -o ./coverage ./coverage/lcov.info
```

Is there a way that I can generate the report that can expand on each file with the cli from the lcov.info file?

**Comment by eugenezinovyev** [comment]
The CLI is also working with the LCOV file that does not contain any source code and thus the resulting report does not contain the source code as well.

However, there is a way to generate a report with the source code. You can install [@lcov-viewer/istanbul-report](https://www.npmjs.com/package/@lcov-viewer/istanbul-report) package, and include it the "coverageReporters" of the Jest configuration.
After that, you can run jest with coverage collection and check the generated report in the coverage folder.

**Comment by fernandopasik** [comment]
oh ok, ideally I'd love to remove jest and go with the new node.js official test runner and unfortunatelly for now it does only generate the lcov.info file.

**Comment by eugenezinovyev** [comment]
@fernandopasik you can use the [c8](https://www.npmjs.com/package/c8) package with the native node.js test runner. You need to install both "c8" and "@lcov-viewer/istanbul-report" and run tests in the following way:
```
c8 --reporter=@lcov-viewer/istanbul-report node --test
```

You also can use this repository as an example: https://github.com/eugenezinovyev/test-runner-lcov-viewer

**Comment by fernandopasik** [comment]
Thank you @eugenezinovyev I've used c8 before, I was hoping to use entirely the new node testing runner but seems coverage still needs a few tweaks.

**Comment by fernandopasik** [comment]
FYI also in node.js repo there was a suggestion that node coverage system doesn't support sourcemaps yet
https://github.com/nodejs/node/issues/49626#issuecomment-1893259080
